version: '3.3'

services:
  mysql:
    container_name: mysqldb
    image: mysql:latest
    #    platform: linux/amd64 # uncomment this if using Apple silicon
    hostname: mysql
    restart: on-faiure
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: timeSheetDevOps

    ports:
      - "3309:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:db
    ports:
      - "3308:80"

  timesheet:
    image: sami291/timesheet
    container_name: timesheet
    build: ./
    restart: on-failure
    ports:
      - "8080:8084"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/timeSheetDevOps?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: 
      #- DEFAULT_PATH=<Target path in windows>
    depends_on:
      - mysql
      - phpmyadmin
